### ISSUE TITLE
Uncaught ReferenceError: m is not defined

### ISSUE THREAD

**Issue by rvdheuvel** [mapbox/rapidDeploy#2]
Hi,

Sounds like a promising project! Just curious to see what the app looks like. Unfortunately I'm getting the following error:

> src.e31bb0bc.js:116 Uncaught ReferenceError: m is not defined
    at Object.parcelRequire.index.js.mapbox-gl (index.js:313)
    at newRequire (src.e31bb0bc.js:47)
    at src.e31bb0bc.js:81
    at src.e31bb0bc.js:120

I'm having this problem in Chrome and old and new Edge. Do you know what might cause this error? The search bar is not visible and the buttons aren't working.

Thanks.

**Comment by cmtoomey** [comment]
@rvdheuvel - can you add some detail as to when you see this error? 

Can you confirm that you ran 
- `npm ci`
- `npm config`
- `npm start`

**Comment by cmtoomey** [comment]
@rvdheuvel - I am able to reproduce. Let me run this down and get a fix in.

**Comment by cmtoomey** [comment]
@rvdheuvel Problem solved - it was a rogue character causing all the mayhem. Should be GTG now. Pull from master and I think problems will be solved.

**Comment by rvdheuvel** [comment]
Unfortunately no luck. Pulled the latest version and confirmed that the `m` was removed. Maybe this server error might help?

> [1] ‼  C:\code\rapiddeploy\node_modules\jsonlint-lines\lib\jsonlint.js:692:44: Cannot statically evaluate fs argument
[1]   690 |         process.exit(1);
[1]   691 |     }
[1] > 692 |     var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
[1]       |                                            ^
[1]   693 |     return exports.parser.parse(source);
[1]   694 | };
[1]   695 | if (typeof module !== 'undefined' && require.main === module) {
[1] √  Built in 17.27s.

**Comment by cmtoomey** [comment]
@rvdheuvel That error is a parcel warning and shouldn't block the build.

**Comment by rvdheuvel** [comment]
Indeed: problem solved 👍
